### PR TITLE
Check minor version tested up

### LINKED ISSUE #885: Check: Don't allow to use minor versions in Tested Up
In our reviews we do not allow to use minor versions in Tested Up header. We ask the autor to change te version like this:

ERROR: Tested up to: "6.7.1" needs to be just the major version number. Example: Tested up: 6.7
ℹ️ Please, include only the major WordPress version, as the minor version is ignored.

So we will have to make the check to accomplish this guideline.

### PR DESCRIPTION
**Pull request by davidperezgar**
Fixes #885

### CODE REVIEW

File: includes/Checker/Checks/Plugin_Repo/Plugin_Readme_Check.php [hunk 1]
```diff
@@ -214,6 +214,23 @@ private function check_headers( Check_Result $result, string $readme_file, Parse
 				if ( ! empty( $parser->{$field_key} ) && 'tested' === $field_key ) {
 					list( $tested_upto, ) = explode( '-', $parser->{$field_key} );
 
+					if ( preg_match( '/^\d+\.\d+\.\d+/', $tested_upto ) ) {
+						$this->add_result_error_for_file(
+							$result,
+							sprintf(
+								/* translators: %s: currently used version */
+								__( '<strong>Tested up to: %s</strong><br>The version number should only include major versions (e.g. 6.7), not minor versions (e.g. 6.7.1).', 'plugin-check' ),
```
Comment (ernilambar) [inline includes/Checker/Checks/Plugin_Repo/Plugin_Readme_Check.php]: I would like version here be dynamic rather than hardcoded 6.7.

File: tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php [hunk 2]
```diff
@@ -491,8 +509,8 @@ public function test_run_with_errors_tested_up_to_latest_plus_two_version() {
 		$filtered_items = wp_list_filter( $errors['readme.md'][0][0], array( 'code' => 'nonexistent_tested_upto_header' ) );
 
 		$this->assertCount( 1, $filtered_items );
-		$this->assertStringContainsString( 'Tested up to: 6.1', $filtered_items[0]['message'] );
-		$this->assertStringContainsString( 'This version of WordPress does not exist (yet).', $filtered_items[0]['message'] );
+		$this->assertStringContainsString( 'Tested up to: 6.1', $filtered_items[1]['message'] );
```
Comment (ernilambar) [inline tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php]: Not sure why this test was affected by the PR.

File: includes/Checker/Checks/Plugin_Repo/Plugin_Readme_Check.php (hunk 1 above)
Comment (davidperezgar) [reply includes/Checker/Checks/Plugin_Repo/Plugin_Readme_Check.php]: That's true. I'll change it. thanks

File: tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php (hunk 2 above)
Comment (davidperezgar) [reply tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php]: Yeap. I think that is because of the array of elements.

**Comment by davidperezgar** [comment]
@ernilambar I'm having this problem:
```
/home/runner/work/plugin-check/plugin-check/includes/Checker/Checks/Plugin_Repo/Plugin_Readme_Check.php:195  ExcessiveMethodLength  The method check_headers() has 100 lines of code. Current threshold is set to 100. Avoid really long methods.
Script phpmd . text phpmd.xml handling the phpmd event returned with error code 2
```
How could avoid that?

**Comment by davidperezgar** [comment]
I've solved. I saw where to avoid that directive.

File: tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php (hunk 2 above)
Comment (ernilambar) [reply tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php]: `$filtered_items = array_values( wp_list_filter( $errors['readme.md'][0][0], array( 'code' => 'nonexistent_tested_upto_header' ) ) );` If we use `array_values()` here we could make test more robust and it will whatever position this exists in the $errors array.

Comment (davidperezgar) [reply tests/phpunit/tests/Checker/Checks/Plugin_Readme_Check_Tests.php]: yes, you're right. thanks

**Comment by ernilambar** [comment]
Screenshot 2025-03-14 at 9 56 04 AM
I think message could be little improved. Like:

```
Tested up to: 6.6.1. The version number should only include major versions 6.6.
```

What do you think?

**Review by ernilambar — APPROVED** [review]

**Review by swissspidy — APPROVED** [review]
