### PR TITLE
CLI Command shows critical error

### LINKED ISSUE #210: CLI Command shows critical error
### Describe the bug

After implementing the `Performant_WP_Query_Params_Check()` check #27, the CLI command now displays a critical error when executed.

Command: `npm run wp-env run cli -- wp plugin check hello.php --require=./wp-content/plugins/plugin-check/cli.php`

### Steps to Reproduce

1. Open terminal
2. Go to /plugin-check folder
3. Run `npm run wp-env run cli -- wp plugin check hello.php --require=./wp-content/plugins/plugin-check/cli.php` in your command promp

### Screenshots, screen recording, code snippet

_No response_

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
### Details for the issue:
After implementing the second check, `Enqueued_Scripts_In_Footer_Check` we encountered issues with our unit tests. This problem also affected the configuration of `PHP_CodeSniffer` ([details here](https://github.com/10up/plugin-check/pull/186#issuecomment-1584433805)).

In the CLI, we experienced the same problem where the sniff config automatically changed to the default setting. As a result, it attempted to run the entire sniff instead of the specific sniff we requested. (Please refer to the attached screenshot for reference.)

Screenshot 2023-06-29 at 11 15 47 AM

The cause of the fatal error is the incompatibility between the VIP-Coding-Standards and the development version of PHPCS. We recently updated the development version, and some of the VIP sniffs still utilize an older version of the function, leading to the generation of a fatal error. (Please see the attached screenshot for more details.)

Screenshot 2023-06-29 at 11 24 42 AM

Closes #210

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] All new and existing tests pass.

### CODE REVIEW

File: includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php [hunk 1]
```diff
@@ -75,6 +75,23 @@ final public function run( Check_Result $result ) {
...
+			 * use class in ReflectionClass.
+			 *
+			 * @phpstan-ignore-next-line
+			 */
+			$reflected_phpcs_config = new \ReflectionClass( '\PHP_CodeSniffer\Config' );
+			$overridden_defaults    = $reflected_phpcs_config->getProperty( 'overriddenDefaults' );
+			$overridden_defaults->setAccessible( true );
+			$overridden_defaults->setValue( array() );
+			$overridden_defaults->setAccessible( false );
+		}
```
Comment (spacedmonkey) [inline includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php]: Personal preference, I would have this logic in a protected method.

**Review by spacedmonkey — APPROVED** [review]
SGTM

File: includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php (hunk 1 above)
Comment (felixarntz) [inline includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php]: @mukeshpanchal27 How does moving this here fix the fatal error? Related is my question in https://github.com/10up/plugin-check/issues/210#issuecomment-1611792431, I'm still unclear what the actual error is. That may help answer my question here.

Just from looking at it, I am a bit confused why we need to copy logic that only applied to tests over to production code. Can you clarify why that is needed?

Comment (mukeshpanchal27) [reply includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php]: Apologies, @felixarntz, for forgetting to mention the updates I made in the PR description. Could you please take a moment to review the changes and let me know if they provide helpful information for the PR review?

Comment (felixarntz) [reply includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php]: Thanks @mukeshpanchal27, it's clear to me now!

Comment (felixarntz) [reply includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php]: @mukeshpanchal27 See above, however it should be a `private` method since there's no reason at this point to expose it to child classes. Can you move this to a method please?

Comment (jjgrainger) [reply includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php]: @mukeshpanchal27 +1 on the above, lets move this to a `private` method.

**Review by jjgrainger — CHANGES_REQUESTED** [review]
@mukeshpanchal27 looks good, just one update to make before approving. See this comment - https://github.com/10up/plugin-check/pull/214/files#r1246910982

File: includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php (hunk 1 above)
Comment (mukeshpanchal27) [reply includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php]: Thanks for the feedback. In https://github.com/10up/plugin-check/pull/214/commits/55a8867d363dbeff1572bb29c2d9dba939e4f8ab i have move the code in `private` mathod.

**Review by jjgrainger — APPROVED** [review]

**Review by felixarntz — APPROVED** [review]
