### PR TITLE
Fix: Fatal error when in checks in `--checks` and `--exclude-checks` overlaps

### LINKED ISSUE #359: Fatal error when in checks in `--checks` and `--exclude-checks` overlaps
Eg:
`wp plugin check hello-dolly --checks=plugin_review_phpcs,late_escaping --exclude-checks=late_escaping`

Our CLI arguments:

    [--exclude-checks=<checks>]
    Exclude checks provided as an argument in comma-separated values, e.g. i18n_usage, late_escaping. Applies after evaluating `--checks.`

Since we are calculating excludes after checks, overlapping of checks in the arguments should not generate fatal error.
In the above example scenario, only `plugin_review_phpcs` should be in the final checks list.

**OR**
If we do not expect both arguments in the same command, we should validate and give `WP_CLI::error()`

Output: 
Screenshot 2024-01-10 at 12 17 28 PM

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
Closes #359

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).

### CODE REVIEW

File: includes/Checker/Abstract_Check_Runner.php [hunk 1]
```diff
@@ -419,9 +419,7 @@ final public function get_checks_to_run() {
 			$collection = Check_Categories::filter_checks_by_categories( $collection, $categories );
 		}
 
-		return $collection
-			->require( $check_slugs ) // Ensures all of the given slugs are valid.
```
Comment (ernilambar) [inline includes/Checker/Abstract_Check_Runner.php:423]: You have removed `require( $check_slugs )`. Are we sure we want to remove validation altogether?

Comment (mukeshpanchal27) [reply includes/Checker/Abstract_Check_Runner.php:423]: Missed that completely nice catch. Reverted in https://github.com/WordPress/plugin-check/pull/387/commits/9fb14284cea537776679592dfd7435965e149b97

**Review by ernilambar — APPROVED** [review]

**Review by swissspidy — APPROVED** [review]

File: includes/Checker/Abstract_Check_Runner.php [hunk 2]
```diff
@@ -420,7 +420,7 @@ final public function get_checks_to_run() {
 		}
 
 		return $collection
-			->require( $check_slugs ) // Ensures all of the given slugs are valid.
+			->require( array_keys( $collection->to_map() ) ) // Ensures all of the given slugs are valid.
```
Comment (felixarntz) [inline includes/Checker/Abstract_Check_Runner.php]: This line is now useless as far as I can tell. The `require()` should be called to avoid people passing check slugs that aren't available.

I think a proper fix would be to instead leave the `require()` as is, but move it between lines 412 and 413, i.e. before the exclusions are applied.

This way the requirement is maintained without causing the error as far as I can tell.

**Review by felixarntz — CHANGES_REQUESTED** [review]
I think the fix here currently breaks another _intentional_ functionality.

File: includes/Checker/Abstract_Check_Runner.php (hunk 2 above)
Comment (mukeshpanchal27) [reply includes/Checker/Abstract_Check_Runner.php]: Thanks for the feedback. Initially i think do that but thanks for pointing. Addressed in https://github.com/WordPress/plugin-check/pull/387/commits/5fc1a149806a3125f4c101ef02603c16a4e9ee3a

**Review by felixarntz — APPROVED** [review]
Thanks @mukeshpanchal27!
