### PR TITLE
Fix the `PHP Warning` for `composer phpstan`

### LINKED ISSUE #296: Fix the `PHP Warning` for `composer phpstan`
## Bug Description

There is a warning when the `composer phpstan` are run on GH and local system.

```
PHP Warning:  Constant WP_PLUGIN_DIR already defined in /home/runner/work/plugin-check/plugin-check/tests/phpstan/bootstrap.php on line 5
``` 

## Steps to reproduce

https://github.com/WordPress/plugin-check/actions/runs/6569961840/job/17846653119

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
Closes #296

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
The error removed now https://github.com/WordPress/plugin-check/actions/runs/6573634827/job/17857069454?pr=297

File: tests/phpstan/bootstrap.php [hunk 1]
```diff
@@ -1,6 +1,6 @@
 <?php
 
-define( 'WP_PLUGIN_CHECK_PLUGIN_DIR_PATH', '' );
-define( 'WP_CONTENT_DIR', '' );
-define( 'WP_PLUGIN_DIR', '' );
-define( 'WP_PLUGIN_CHECK_PLUGIN_DIR_URL', '' );
+defined( 'WP_PLUGIN_CHECK_PLUGIN_DIR_PATH' ) or define( 'WP_PLUGIN_CHECK_PLUGIN_DIR_PATH', '' );
+defined( 'WP_CONTENT_DIR' ) or define( 'WP_CONTENT_DIR', '' );
+defined( 'WP_PLUGIN_DIR' ) or define( 'WP_PLUGIN_DIR', '' );
+defined( 'WP_PLUGIN_CHECK_PLUGIN_DIR_URL' ) or define( 'WP_PLUGIN_CHECK_PLUGIN_DIR_URL', '' );
```
Comment (swissspidy) [inline tests/phpstan/bootstrap.php]: That's really not the way to do it. This file is for making PHPStan aware of WP-specific constants.

Since https://github.com/szepeviktor/phpstan-wordpress/pull/193 it already knows about `WP_PLUGIN_DIR` so we can simply remove the definition here.


```suggestion
define( 'WP_PLUGIN_CHECK_PLUGIN_DIR_PATH', '' );
define( 'WP_CONTENT_DIR', '' );
define( 'WP_PLUGIN_CHECK_PLUGIN_DIR_URL', '' );
```

**Review by swissspidy — APPROVED** [review]

**Review by felixarntz — APPROVED** [review]
