### PR TITLE
Fix Runtime Checks in CLI

### LINKED ISSUE #133: Database errors when running a Runtime check via CLI.
When testing the CLI command errors appears in the command output but did not interrupt the command. These errors only appeared when a Runtime check was to be run.

Errors related to the test database tables that are created during in the [Runtime_Environment_Setup](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Runtime_Environment_Setup.php#L22).

I believe this is because the [Runners prepare()](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Abstract_Check_Runner.php#L150) method is run ([on `muplugins_loaded` action](https://github.com/10up/plugin-check/blob/trunk/includes/Utilities/Plugin_Request_Utility.php#L96-L102)) before the [Runtime_Environment_Setup::setup()](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Runtime_Environment_Setup.php#L22) is called (in the [Plugin_Check_Command](https://github.com/10up/plugin-check/blob/trunk/includes/CLI/Plugin_Check_Command.php#L135)). But this needs further investigation.

Example of the error can be seen here:

```
WordPress database error Table 'wordpress.wppc_options' doesn't exist for query SELECT option_value FROM wppc_options WHERE option_name = 'WPLANG' LIMIT 1 made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), include_once('/plugins/test-plugin-check-errors/test-plugin-check-errors.php'), __, translate, get_translations_for_domain, _load_textdomain_just_in_time, _get_path_to_translation, _get_path_to_translation_from_lang_dir, determine_locale, get_locale, get_option
<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [Table &#039;wordpress.wppc_options&#039; doesn&#039;t exist]<br /><code>SELECT option_value FROM wppc_options WHERE option_name = &#039;WPLANG&#039; LIMIT 1</code></p></div>[05-Apr-2023 13:43:47 UTC] WordPress database error Table 'wordpress.wppc_options' doesn't exist for query SELECT option_value FROM wppc_options WHERE option_name = 'wppc_user_roles' LIMIT 1 made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), WP_Roles->__construct, WP_Roles->for_site, WP_Roles->get_roles_data, get_option
<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [Table &#039;wordpress.wppc_options&#039; doesn&#039;t exist]<br /><code>SELECT option_value FROM wppc_options WHERE option_name = &#039;wppc_user_roles&#039; LIMIT 1</code></p></div>[05-Apr-2023 13:43:47 UTC] WordPress database error Table 'wordpress.wppc_options' doesn't exist for query SELECT option_value FROM wppc_options WHERE option_name = 'can_compress_scripts' LIMIT 1 made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, wp_widgets_init, do_action('widgets_init'), WP_Hook->do_action, WP_Hook->apply_filters, WP_Widget_Factory->_register_widgets, WP_Widget->_register, WP_Widget_Text->_register_one, wp_add_inline_script, wp_scripts, WP_Scripts->__construct, WP_Scripts->init, do_action_ref_array('wp_default_scripts'), WP_Hook->do_action, WP_Hook->apply_filters, wp_default_packages, wp_register_tinymce_scripts, script_concat_settings, get_site_option, get_network_option, get_option
<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [Table &#039;wordpress.wppc_options&#039; doesn&#039;t exist]<br /><code>SELECT option_value FROM wppc_options WHERE option_name = &#039;can_compress_scripts&#039; LIMIT 1</code></p></div>[05-Apr-2023 13:43:47 UTC] WordPress database error Table 'wordpress.wppc_options' doesn't exist for query SELECT option_value FROM wppc_options WHERE option_name = 'theme_switched' LIMIT 1 made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), do_action('init'), WP_Hook->do_action, WP_Hook->apply_filters, check_theme_switched, get_option
<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [Table &#039;wordpress.wppc_options&#039; doesn&#039;t exist]<br /><code>SELECT option_value FROM wppc_options WHERE option_name = &#039;theme_switched&#039; LIMIT 1</code></p></div>[05-Apr-2023 13:43:47 UTC] WordPress database error Table 'wordpress.wppc_options' doesn't exist for query SELECT option_value FROM wppc_options WHERE option_name = 'medium_crop' LIMIT 1 made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, {closure}, {closure}, WP_Theme_JSON_Resolver::get_merged_data, WP_Theme_JSON_Resolver::get_theme_data, get_default_block_editor_settings, wp_get_registered_image_subsizes, get_option
<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [Table &#039;wordpress.wppc_options&#039; doesn&#039;t exist]<br /><code>SELECT option_value FROM wppc_options WHERE option_name = &#039;medium_crop&#039; LIMIT 1</code></p></div>[05-Apr-2023 13:43:47 UTC] WordPress database error Table 'wordpress.wppc_options' doesn't exist for query SELECT option_value FROM wppc_options WHERE option_name = 'medium_large_crop' LIMIT 1 made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, {closure}, {closure}, WP_Theme_JSON_Resolver::get_merged_data, WP_Theme_JSON_Resolver::get_theme_data, get_default_block_editor_settings, wp_get_registered_image_subsizes, get_option
<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [Table &#039;wordpress.wppc_options&#039; doesn&#039;t exist]<br /><code>SELECT option_value FROM wppc_options WHERE option_name = &#039;medium_large_crop&#039; LIMIT 1</code></p></div>[05-Apr-2023 13:43:47 UTC] WordPress database error Table 'wordpress.wppc_options' doesn't exist for query SELECT option_value FROM wppc_options WHERE option_name = 'large_crop' LIMIT 1 made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, {closure}, {closure}, WP_Theme_JSON_Resolver::get_merged_data, WP_Theme_JSON_Resolver::get_theme_data, get_default_block_editor_settings, wp_get_registered_image_subsizes, get_option
<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [Table &#039;wordpress.wppc_options&#039; doesn&#039;t exist]<br /><code>SELECT option_value FROM wppc_options WHERE option_name = &#039;large_crop&#039; LIMIT 1</code></p></div>[05-Apr-2023 13:43:47 UTC] WordPress database error Table 'wordpress.wppc_terms' doesn't exist for query
			SELECT  t.term_id
			FROM wppc_terms AS t  INNER JOIN wppc_term_taxonomy AS tt ON t.term_id = tt.term_id
			WHERE tt.taxonomy IN ('wp_theme') AND t.name IN ('wp-empty-theme')

			LIMIT 1
		 made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, {closure}, {closure}, WP_Theme_JSON_Resolver::get_merged_data, WP_Theme_JSON_Resolver::get_user_data, WP_Theme_JSON_Resolver::get_user_data_from_wp_global_styles, wp_get_recent_posts, get_posts, WP_Query->query, WP_Query->get_posts, WP_Tax_Query->get_sql, WP_Tax_Query->get_sql_clauses, WP_Tax_Query->get_sql_for_query, WP_Tax_Query->get_sql_for_clause, WP_Tax_Query->clean_query, WP_Tax_Query->transform_query, WP_Term_Query->query, WP_Term_Query->get_terms
<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [Table &#039;wordpress.wppc_terms&#039; doesn&#039;t exist]<br /><code>
			SELECT  t.term_id
			FROM wppc_terms AS t  INNER JOIN wppc_term_taxonomy AS tt ON t.term_id = tt.term_id
			WHERE tt.taxonomy IN (&#039;wp_theme&#039;) AND t.name IN (&#039;wp-empty-theme&#039;)

			LIMIT 1
		</code></p></div>[05-Apr-2023 13:43:47 UTC] WordPress database error Table 'wordpress.wppc_posts' doesn't exist for query
					SELECT   wppc_posts.ID
					FROM wppc_posts
					WHERE 1=1  AND (
  0 = 1
) AND wppc_posts.post_type = 'wp_global_styles' AND ((wppc_posts.post_status = 'publish'))
					GROUP BY wppc_posts.ID
					ORDER BY wppc_posts.post_date DESC
					LIMIT 0, 1
				 made by include('phar:///usr/local/bin/wp/php/boot-phar.php'), include('phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php'), WP_CLI\bootstrap, WP_CLI\Bootstrap\LaunchRunner->process, WP_CLI\Runner->start, WP_CLI\Runner->load_wordpress, require('wp-settings.php'), do_action('wp_loaded'), WP_Hook->do_action, WP_Hook->apply_filters, {closure}, {closure}, WP_Theme_JSON_Resolver::get_merged_data, WP_Theme_JSON_Resolver::get_user_data, WP_Theme_JSON_Resolver::get_user_data_from_wp_global_styles, wp_get_recent_posts, get_posts, WP_Query->query, WP_Query->get_posts
<div id="error"><p class="wpdberror"><strong>WordPress database error:</strong> [Table &#039;wordpress.wppc_posts&#039; doesn&#039;t exist]<br /><code>
					SELECT   wppc_posts.ID
					FROM wppc_posts
					WHERE 1=1  AND (
  0 = 1
) AND wppc_posts.post_type = &#039;wp_global_styles&#039; AND ((wppc_posts.post_status = &#039;publish&#039;))
					GROUP BY wppc_posts.ID
					ORDER BY wppc_posts.post_date DESC
					LIMIT 0, 1
</code></p></div>

```

### LINKED ISSUE #134: Runtime checks do not run in CLI
Looking into this further I found that the [`is_plugin_active`](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Abstract_Check_Runner.php#L260) returns `true` on every call in the process except for the very last call where it returns `false`. The below is the current run order.

1. [`Abstract_Check_Runner::prepare()`](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Abstract_Check_Runner.php#L151) - Plugin is seen as active, both runtime and static checks are returned. This is called on the [`muplugins_active` action](https://github.com/10up/plugin-check/blob/trunk/includes/Utilities/Plugin_Request_Utility.php#L96-L102).
2. [Plugin_Check_Command::check()](https://github.com/10up/plugin-check/blob/trunk/includes/CLI/Plugin_Check_Command.php#L127) - Getting the checks instances to check if the runtime environment setup is needed. Plugin active, both runtime and static checks returned.
3. [Abstract_Check_Runner::run()](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Abstract_Check_Runner.php#L177) - Finally run the checks in the [Plugin_Check_Command](https://github.com/10up/plugin-check/blob/trunk/includes/CLI/Plugin_Check_Command.php#L140). Plugin is **inactive**, only the static check returned.

My current thinking is the `Runtime_Environment_Setup` is impacting this as it's run just before the `Abstract_Check_Runner::run()`. So there could be a conflict between the `Runtime_Environment_Setup` and the `Universal_Runtime_Preparation` or the ordering of the setup and preparations needs correcting (see #133)

I have been able to confirm that the runtime checks do work as expected when run and results displayed are correct. However, this was hack to get this working.

### PR DESCRIPTION
**Pull request by jjgrainger**
This resolves both the database errors and runtime checks not being run via the CLI. I've taken the shortest approach to resolve this for now but we can discuss if we want to alter/expand on this approach based on other issues.

The runtime checks did not run as the plugin was not active in the test database tables. The `update_option` in the `Runtime_Environment_Setup` fixes this.

The database errors were caused by the `Universal_Runtime_Preparations` being run ahead of the Runtime Environment being setup. As the Runtime Environment is setup manually late in the process I've opted to calling the `Universal_Runtime_Preparations` within the runners `run()` method. We may however want to review this alongside #128 to see if the `Runtime_Environment_Setup` can be run earlier in the process.

closes #134, closes #133

### CODE REVIEW

File: includes/Checker/Abstract_Check_Runner.php [hunk 1]
```diff
@@ -178,13 +178,19 @@ public function run() {
 		$preparations = $this->get_shared_preparations( $checks );
 		$cleanups     = array();
 
+		// Prepare the universal runtime preparations if required.
+		$cleanups[] = $this->prepare();
```
Comment (spacedmonkey) [inline includes/Checker/Abstract_Check_Runner.php]:
```suggestion
		$cleanups     = array(
		   $this->prepare() // Prepare the universal runtime preparations if required.
		); 
```

File: includes/Utilities/Plugin_Request_Utility.php [hunk 2]
```diff
@@ -93,14 +93,7 @@ public static function initialize_runner() {
...
 			if ( $runner->is_plugin_check() ) {
-				add_action(
-					'muplugins_loaded',
-					function() use ( $runner ) {
-						static::$cleanup = $runner->prepare();
-						static::$runner  = $runner;
-					}
-				);
-
+				static::$runner = $runner;
```
Comment (felixarntz) [inline includes/Utilities/Plugin_Request_Utility.php]: Can you explain the rationale behind this change? I see you moved the runner `prepare()` call into `Abstract_Check_Runner::run()`, however isn't that too late? The `Universal_Runtime_Preparation` filters the list of active plugins, which has to happen before WordPress loads plugins, which is why here it happens on `muplugins_loaded`.

Getting rid of that will break that behavior I think.

**Review by felixarntz — CHANGES_REQUESTED** [review]
@jjgrainger I think there is a problem with this fix as it moves the `Universal_Runtime_Preparation::prepare()` call to happen too late, unless I'm missing something.

Potentially your alternative solution related to #128 is the only way forward here.

File: includes/Utilities/Plugin_Request_Utility.php (hunk 2 above)
Comment (jjgrainger) [reply includes/Utilities/Plugin_Request_Utility.php]: @felixarntz I think you're right and this is something I overlooked in the changes here. This should be reverted.

However, I think this highlights that the Runtime_Environment_Setup needs to be run earlier in the process as before the runners prepare method is called as this is what's causing the errors. I'll update this PR and investigate this further here.

File: includes/Checker/Abstract_Check_Runner.php (hunk 1 above)
Comment (jjgrainger) [reply includes/Checker/Abstract_Check_Runner.php]: Thanks @spacedmonkey the original changes made were reverted so we no longer call the `prepare()` method here.

**Comment by jjgrainger** [comment]
@felixarntz @spacedmonkey I now believe the DB errors were caused by setting the database prefix too early. I've reverted my previous changes and updated the PR to set the prefix before the shared preparations are run. Again, this seems like the quickest way to resolve this but we may want to refactor this further as part of https://github.com/10up/plugin-check/issues/128

This is ready for review

File: includes/Checker/Abstract_Check_Runner.php [hunk 3]
```diff
@@ -174,10 +164,18 @@ public function prepare() {
...
 	public function run() {
+		global $wpdb, $table_prefix;
 		$checks       = $this->get_checks_to_run();
 		$preparations = $this->get_shared_preparations( $checks );
 		$cleanups     = array();
+		$old_prefix   = null;
 
+		// Set the correct test database prefix if required.
+		if ( $this->has_runtime_check( $checks ) ) {
+			$old_prefix = $wpdb->set_prefix( $table_prefix . 'pc_' );
```
Comment (felixarntz) [inline includes/Checker/Abstract_Check_Runner.php:175]: Unrelated to this PR, but seeing the logic to set the prefix (and to restore it further below) makes me think it would be good to move this logic into a new `Preparation`, e.g. `Use_Check_Tables_Preparation`. That would be a very small class, but it would be good to put the logic in there.

We can do that separately and it isn't urgent, but would be great to open an issue for it.

**Review by felixarntz — APPROVED** [review]
Thanks @jjgrainger, great catch!

One comment below, however that should be decoupled and happen separately.

**Review by spacedmonkey — APPROVED** [review]

File: includes/Checker/Abstract_Check_Runner.php (hunk 3 above)
Comment (jjgrainger) [reply includes/Checker/Abstract_Check_Runner.php:175]: Thanks @felixarntz I've created a new issue for this here https://github.com/10up/plugin-check/issues/159
