### PR TITLE
Fix responsive table results

### LINKED ISSUE #281: We need to fix mobile UI on plugin check page
### Describe the bug

Hi Team,

The plugin is really very good at decreasing basic testing for all submitted plugin authors. I have checked some UI (button alignment, text wrap, and other ) issues on mobile devices. i am sharing a screenshot here.

Thank you

### Steps to Reproduce

1. Go to the Plugin Check submenu
2. check any plugin
3. then you can see mentioned screenshot UI issue

### Screenshots, screen recording, code snippet

Plugin-Check-‹-wpextended-—-WordPress

### Environment information

- Device - Ubuntu 20.04.6 LTS
- Browser - Google Chrome

### WordPress information

`
### wp-core ###

version: 6.3
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 2
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /var/www/html/wpextended
wordpress_size: 52.07 MB (54594415 bytes)
uploads_path: /var/www/html/wpextended/wp-content/uploads
uploads_size: 38.68 MB (40563024 bytes)
themes_path: /var/www/html/wpextended/wp-content/themes
themes_size: 14.04 MB (14726026 bytes)
plugins_path: /var/www/html/wpextended/wp-content/plugins
plugins_size: 122.67 MB (128629458 bytes)
database_size: 2.70 MB (2834432 bytes)
total_size: 230.17 MB (241347355 bytes)

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 2.2
author: the WordPress team
author_website: https://wordpress.org/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, responsive-embeds, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, editor-styles, widgets, menus, editor-style
theme_path: /var/www/html/wpextended/wp-content/themes/twentytwenty
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Twenty-One: version: 1.8, author: the WordPress team, Auto-updates disabled
Twenty Twenty-Three: version: 1.0, author: the WordPress team (latest version: 1.2), Auto-updates disabled
Twenty Twenty-Two: version: 1.4, author: the WordPress team, Auto-updates disabled

### wp-plugins-active (3) ###

Advanced Custom Fields: version: 6.2.0, author: WP Engine (latest version: 6.2.1), Auto-updates disabled
Plugin Check: version: 0.2.1, author: Plugin Review Team, Auto-updates disabled
WPExtended: version: 2.4.4, author: WP Extended, Auto-updates disabled

### wp-plugins-inactive (24) ###

Admin and Site Enhancements: version: 5.2.10, author: Bowo (latest version: 5.7.1), Auto-updates disabled
Admin Login Notification: version: 1.0, author: Sumit Singh, Auto-updates disabled
Akismet Anti-Spam: Spam Protection: version: 5.2, author: Automattic - Anti Spam Team (latest version: 5.3), Auto-updates disabled
BuddyPress: version: 11.1.0, author: The BuddyPress Community (latest version: 11.3.1), Auto-updates disabled
Classic Editor: version: 1.6.3, author: WordPress Contributors, Auto-updates disabled
Contact Form 7: version: 5.7.5.1, author: Takayuki Miyoshi (latest version: 5.8), Auto-updates disabled
Custom Comment Validation: version: 1.0, author: Sumit Singh, Auto-updates disabled
Custom Post Type UI: version: 1.13.6, author: WebDevStudios (latest version: 1.14.0), Auto-updates disabled
Disable Blog: version: 0.5.3, author: Joshua David Nelson, Auto-updates disabled
Disable Blogging: version: 2.1.0, author: Fact Maven, Auto-updates disabled
Elementor: version: 3.12.2, author: Elementor.com (latest version: 3.16.4), Auto-updates disabled
GitHub Issues List: version: 1.0.0, author: Sumit Singh, Auto-updates disabled
Hello Dolly: version: 1.7.2, author: Matt Mullenweg, Auto-updates disabled
Maintenance: version: 4.07, author: WebFactory Ltd (latest version: 4.08), Auto-updates disabled
Post Types Order: version: 2.0.5, author: Nsp Code (latest version: 2.1), Auto-updates disabled
Query Monitor: version: 3.12.2, author: John Blackbourn (latest version: 3.13.1), Auto-updates disabled
Safe SVG: version: 2.1.1, author: 10up (latest version: 2.2.0), Auto-updates disabled
User Role Editor: version: 4.63.3, author: Vladimir Garagulya (latest version: 4.64), Auto-updates disabled
User Switching: version: 1.7.0, author: John Blackbourn & contributors, Auto-updates disabled
Visual Composer: version: 45.1.3, author: visualcomposer.com (latest version: 45.5.0), Auto-updates disabled
WordPress Beta Tester: version: 3.5.2, author: WordPress Upgrade/Install Team (latest version: 3.5.4), Auto-updates disabled
WordPress Importer: version: 0.7, author: wordpressdotorg (latest version: 0.8.1), Auto-updates disabled
WP Extended SMTP: version: 1.0, author: Sumit Singh, Auto-updates disabled
WP File Manager: version: 7.1.8, author: mndpsingh287 (latest version: 7.2), Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 8M
upload_max_filesize: 2M
max_effective_size: 2 MB
max_file_uploads: 20
gd_version: 2.2.5
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: 9.50

### wp-server ###

server_architecture: Linux 5.15.0-84-generic x86_64
httpd_software: Apache/2.4.41 (Ubuntu)
php_version: 7.4.3-4ubuntu2.19 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 2M
php_post_max_size: 8M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false
current: 2023-09-25T09:42:19+00:00
utc-time: Monday, 25-Sep-23 09:42:19 UTC
server-time: 2023-09-25T09:42:16+00:00

### wp-database ###

extension: mysqli
server_version: 8.0.34-0ubuntu0.20.04.1
client_version: mysqlnd 7.4.3-4ubuntu2.19
max_allowed_packet: 67108864
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wpextended/wp-content
WP_PLUGIN_DIR: /var/www/html/wpextended/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by davidperezgar**
Fixes #281

### CODE REVIEW

**Comment by davidperezgar** [comment]
I've added CSS and Data labels to make more comprehensive.
The results from this:
responsive-init

To this:
responsive-fixed

File: templates/results-row.php [hunk 1]
```diff
@@ -1,17 +1,17 @@
 <tr class="plugin-check__results-row">
-	<td>
+	<td data-label="<?php esc_html_e( 'Line', 'plugin-check' ); ?>">
```
Comment (swissspidy) [inline templates/results-row.php]: Why not `esc_attr` since it's within an attribute?

File: assets/css/plugin-check-admin.css [hunk 2]
```diff
@@ -0,0 +1,52 @@
...
+    display: block;
+    font-size: .8em;
+    text-align: right;
+  }
+  
+  table.plugin-check__results-table td::before {
+    content: attr(data-label);
+    float: left;
+    font-weight: bold;
+    text-transform: uppercase;
```
Comment (swissspidy) [inline assets/css/plugin-check-admin.css]: Why uppercase?

File: assets/css/plugin-check-admin.css [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+  table.plugin-check__results-table td {
+    border-bottom: 1px solid #ddd;
+    display: block;
+    font-size: .8em;
+    text-align: right;
+  }
+  
+  table.plugin-check__results-table td::before {
+    content: attr(data-label);
+    float: left;
```
Comment (swissspidy) [inline assets/css/plugin-check-admin.css:48]: When using floats we'll need an RTL version too so that the layout works well when using a different text direction.

File: assets/css/plugin-check-admin.css [hunk 4]
```diff
@@ -0,0 +1,52 @@
+/* Responsive table */
+@media only screen and (max-width: 40em) {
```
Comment (swissspidy) [inline assets/css/plugin-check-admin.css]: Why specifically 40em?

File: templates/results-row.php (hunk 1 above)
Comment (davidperezgar) [reply templates/results-row.php]: ok

File: assets/css/plugin-check-admin.css (hunk 2 above)
Comment (davidperezgar) [reply assets/css/plugin-check-admin.css]: for nothing special. I've removed.

File: assets/css/plugin-check-admin.css (hunk 3 above)
Comment (davidperezgar) [reply assets/css/plugin-check-admin.css:48]: Ok!

File: assets/css/plugin-check-admin.css (hunk 4 above)
Comment (davidperezgar) [reply assets/css/plugin-check-admin.css]: Any size that is mobile. We can do 400px. But what would be your suggestion?

Comment (swissspidy) [reply assets/css/plugin-check-admin.css]: WordPress admin uses `@media screen and (max-width: 782px)` elsewhere for example.

Comment (davidperezgar) [reply assets/css/plugin-check-admin.css]: let's do that.

**Comment by ernilambar** [comment]
Screenshot 2024-09-30 at 9 57 00 AM

I tested PR in my local setup. May be we can reduce font size for the text inside code tag. Other looks good.

**Comment by davidperezgar** [comment]
done!

**Review by swissspidy — APPROVED** [review]

**Review by ernilambar — APPROVED** [review]
