### PR TITLE
Include Translation to the strings that were missing.

### LINKED ISSUE #270: checks/readme.php missing translation functions
### Describe the bug

After translating the plugin into German, part of the test results is shown in English. It seems, the file `check/readme.php` is missing translation functions. Unfortunately I couldn't find this plugin file in the repo and therfor can't submit a pull request.

screenshot_000842@2x

### Steps to Reproduce

Activate plugin in WordPress with language set to German.

### Screenshots, screen recording, code snippet

see above

### Environment information

MacOS Ventura, Firefox

### WordPress information

WordPress 6.3.1, plain vanilla test environment.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bordoni**
Resolves #270.

### CODE REVIEW

File: checks/phpcs.php [hunk 1]
```diff
@@ -113,6 +113,7 @@ protected function phpcs_result_to_warnings( $result ) {
 
 				if ( current_user_can( 'edit_plugins' ) ) {
 					$edit_link   = sprintf(
+						/* translators: 1: URL to edit 2: Title of the Anchor 3: Aria Label 4: Text of the Anchor */
```
Comment (EvanHerman) [inline checks/phpcs.php]: @bordoni This isn't needed here since the line beneath it isn't being translated.

File: checks/phpcs.php [hunk 2]
```diff
@@ -127,7 +128,8 @@ protected function phpcs_result_to_warnings( $result ) {
 				$return[] = new $notice_class(
 					$message['source'],
 					sprintf(
-						'%s Line %d of file %s.<br>%s.<br>%s%s',
+						/* translators: 1: Type of Error 2: Line 3: File 4: Message 5: Code Example 6: Edit Link */
+						'%1$s Line %2$d of file %3$s.<br>%4$s.<br>%5$s%6$s',
```
Comment (EvanHerman) [inline checks/phpcs.php]: @bordoni This line should be wrapped in `__()` if we want it to be translatable.
