### PR TITLE
Remove `Check this plugin` action link from Drop-ins and MU Plugins

### LINKED ISSUE #218: Remove `Check this plugin` action link from Drop-ins and MU Plugins
### Describe the bug

I discovered an issue with the "Check this plugin" action link in the Plugin Checker feature. Currently, this action link is available for the Drop-ins and MU Plugins, but it is unusable as we are unable to test the Drop-ins and MU Plugins functionality. To enhance the usability and overall user experience, I suggest removing the "Check this plugin" action link from the Drop-ins and MU Plugins.

Related: #213

### Steps to Reproduce

1. Go go Admin Panel
2. Install and activate plugin which generate Drop-ins (Performance Lab Or Query Monitor)
3. Go to `/wp-admin/plugins.php?plugin_status=dropins` or `/wp-admin/plugins.php?plugin_status=mustuse`
4. `Check this plugin` action link present.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
Closes #218 

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] Add unit test

### CODE REVIEW

File: includes/Admin/Admin_Page.php [hunk 1]
```diff
@@ -164,11 +164,19 @@ public function render_page() {
 	 *
 	 * @since n.e.x.t
 	 *
+	 * @global string $status
+	 *
 	 * @param array  $actions     List of actions.
 	 * @param string $plugin_file Plugin main file.
 	 * @return array The modified list of actions.
 	 */
 	public function filter_plugin_action_links( $actions, $plugin_file ) {
```
Comment (swissspidy) [inline includes/Admin/Admin_Page.php]: The [`plugin_action_links`](https://developer.wordpress.org/reference/hooks/plugin_action_links/) filter has two additional parameters that both seem to provide the status information. I'd suggest using one of those instead of a global variable.

The third param, `$plugin_data`, is the complete data array for each plugin and has a `status` entry.

The fourth param, `$context`, just provides that same information.

Comment (mukeshpanchal27) [reply includes/Admin/Admin_Page.php]: Thank you, @swissspidy, for your valuable feedback. I took into consideration the use of the `$status` global variable in various places within the WordPress core. However, I have now updated the PR to incorporate your suggestion. The PR now utilizes the filter parameter as recommended.

**Comment by spacedmonkey** [comment]
Love to see a new unit test for this.

**Comment by mukeshpanchal27** [comment]
@spacedmonkey, In https://github.com/10up/plugin-check/pull/221/commits/ce576b0ad0a9ad560e38dfbb8f2ec940bf7ac825 i have added unit test.

**Review by felixarntz — APPROVED** [review]
Thanks @mukeshpanchal27, LGTM!

**Review by swissspidy — APPROVED** [review]

**Review by jjgrainger — APPROVED** [review]
Thanks @mukeshpanchal27 looks good
