### PR TITLE
Fix PHPCS check when testing a single file plugin

### LINKED ISSUE #135: PHPCS Checks will run against all plugins when testing against a single file plugin
When testing against a single file plugin like Hello Dolly, the `Abstract_PHP_CodeSniffer_Check` will run the sniff against all plugins installed. I believe this is due to the [path passed to PHPCS](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Checks/Abstract_PHP_CodeSniffer_Check.php#L74) will result in the plugin directory as the plugins file is omitted from the path.

We should look at updated the [`Plugin_Context`](https://github.com/10up/plugin-check/blob/trunk/includes/Plugin_Context.php) or [`Check_Context`](https://github.com/10up/plugin-check/blob/trunk/includes/Checker/Check_Context.php) with logic to determine if this is a single file plugin and return the correct plugin folder or file.

### PR DESCRIPTION
**Pull request by jjgrainger**
Added a `location()` method to the `Plugin_Context` class to return the correct location for running PHPCS sniffs if checking a single file plugin or folder.

- I'm not 100% sure on the method name and open to suggestions.
- Alternatively, the logic could be handled inside the `Abstract_PHP_CodeSniffer_Check` if we think a method is not needed.

Closes #135

### CODE REVIEW

File: includes/Plugin_Context.php [hunk 1]
```diff
@@ -67,4 +67,22 @@ public function path( $relative_path = '/' ) {
...
+	 *
+	 * @since n.e.x.t
+	 *
+	 * @return string The plugin file if single file plugin. Or the plugin folder.
+	 */
+	public function location() {
+		$path = $this->path();
+
+		// Return the plugin path and basename if the path matches the plugin directory.
+		if ( WP_PLUGIN_DIR . '/' === $path ) {
```
Comment (spacedmonkey) [inline includes/Plugin_Context.php:82]: What about MU plugins?

File: includes/Plugin_Context.php [hunk 2]
```diff
@@ -67,4 +67,22 @@ public function path( $relative_path = '/' ) {
...
+			return $path . $this->basename();
+		}
+
+		return $path;
```
Comment (spacedmonkey) [inline includes/Plugin_Context.php:86]: Should this work instead. 

```
return str_replace( $this->main_file, '',  plugin_dir_path( $this->main_file ) );

File: includes/Plugin_Context.php (hunk 1 above)
Comment (felixarntz) [reply includes/Plugin_Context.php:82]: We don't support testing MU plugins at this point, so this is okay as is I think. Testing MU plugins will require lots of additional changes, so let's think about that separately in the future.

**Review by felixarntz — APPROVED** [review]
@jjgrainger Thanks, LGTM.

Please consider @spacedmonkey's feedback though.

File: includes/Plugin_Context.php (hunk 1 above)
Comment (mukeshpanchal27) [reply includes/Plugin_Context.php:82]: @jjgrainger Do we needs to open separate issue for MU plugins?

File: includes/Plugin_Context.php (hunk 2 above)
Comment (mukeshpanchal27) [reply includes/Plugin_Context.php:86]: @spacedmonkey The above code did not work for the single file plugin.

**Review by mukeshpanchal27 — APPROVED** [review]

File: includes/Plugin_Context.php (hunk 1 above)
Comment (jjgrainger) [reply includes/Plugin_Context.php:82]: Thanks @mukeshpanchal27 @spacedmonkey I've opened an issue to discuss MU Plugin support here https://github.com/10up/plugin-check/issues/154

File: includes/Plugin_Context.php (hunk 2 above)
Comment (jjgrainger) [reply includes/Plugin_Context.php:86]: Thanks @spacedmonkey 

I'm not sure if I've understood your suggestion entirely, but I don't think the suggestion works in this case.

We use the `plugin_dir_path` in the `path()` method so both `$path` and your suggestion are pretty much the same here. The `plugin_dir_path` also removes the plugin main file and returns the plugins folder so I don't think the `str_replace` would do anything?

Let me know if I've misunderstood your suggestion here.

File: includes/Plugin_Context.php (hunk 1 above)
Comment (felixarntz) [reply includes/Plugin_Context.php:82]: Fair point, though at this point testing MU plugins is out of scope. We can consider adding support in the future, but it will involve notably more than just this change, e.g. we have to fix loading order of the code etc. to work for MU plugins which will be even more challenging than it has been for regular plugins.

File: includes/Plugin_Context.php (hunk 2 above)
Comment (spacedmonkey) [reply includes/Plugin_Context.php:86]: Nevermind

**Review by spacedmonkey — APPROVED** [review]
