### PR TITLE
fix: regognize EUPL as GPL compatible license

### LINKED ISSUE #1262: EUPL-1.2 is not recognized as compatible license
https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses

### PR DESCRIPTION
**Pull request by Menrath**
fixes https://github.com/WordPress/plugin-check/issues/1262

### CODE REVIEW

**Comment by ernilambar** [comment]
@Menrath Thanks for the PR. You can take earlier merged PR for adding new license and its related PHP unit tests. https://github.com/WordPress/plugin-check/pull/1158

**Comment by Menrath** [comment]
@ernilambar Thanks for pointing out the other PR, I adjusted this PR accordingly.

**Comment by davidperezgar** [comment]
Hello, you need to fix the code for the tests...

**Comment by Menrath** [comment]
@davidperezgar I would need to fix more of the code, first normalizing and then validating is just not safe. 

Just EUPL is no guarantee that it is GPL compatible. But EUPL-1.1 or EUPL-1.2 is. But maybe this detail is not that important in this case.

**Comment by Menrath** [comment]
Tests pass now. But note that a former test changed in https://github.com/WordPress/plugin-check/pull/1263/commits/c75274039c7a5ee974089c315fce1101ca2aa3d8

**Review by davidperezgar — APPROVED** [review]

File: tests/phpunit/testdata/plugins/test-plugin-eupl-license/load.php [hunk 1]
```diff
@@ -0,0 +1,12 @@
+<?php
+/**
+ * Plugin Name: Test Plugin with WTFPL License
```
Comment (ernilambar) [inline tests/phpunit/testdata/plugins/test-plugin-eupl-license/load.php]:
```suggestion
 * Plugin Name: Test Plugin with EUPL License
```

File: tests/phpunit/testdata/plugins/test-plugin-eupl-license/load.php [hunk 2]
```diff
@@ -0,0 +1,12 @@
...
+ * Plugin URI:  https://wordpress.org/plugins/test-plugin/
+ * Description: Test plugin for WTFPL license validation.
```
Comment (ernilambar) [inline tests/phpunit/testdata/plugins/test-plugin-eupl-license/load.php]:
```suggestion
 * Description: Test plugin for EUPL license validation.
```

File: includes/Traits/License_Utils.php [hunk 3]
```diff
@@ -47,13 +47,13 @@ protected function get_normalized_license( $license ) {
 				}
 			}
 		}
-
```
Comment (ernilambar) [inline includes/Traits/License_Utils.php:50]: This looks unrelated change.

**Comment by Menrath** [comment]
@ernilambar Thanks for catching all those typos, I'll applied all your suggestions.

**Review by ernilambar — APPROVED** [review]
