### PR TITLE
Long lines of code with PHPCS check no longer expand over the size of the notice

### LINKED ISSUE #263: <pre> tags do not wrap properly in the PHPCS errors
### Describe the bug

The `<pre>` tags do not wrap properly and extend beyond the width of the browser window.

### Steps to Reproduce

1. Go to the plugin check page and run the plugin check on a plugin with a PHPCS warning or error.
2. If the text doesn't extend beyond the width of the error div then zoom in on the browser (command and + on a mac).
3. Continue to zoom in until the text extends beyond the width of the browser.

### Screenshots, screen recording, code snippet

image

image

### Environment information

_No response_

### WordPress information

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bordoni**
Resolves #263

### CODE REVIEW

File: admin/admin.php [hunk 1]
```diff
@@ -18,6 +18,20 @@ function render_page() {
...
+			white-space:pre-wrap;
+			word-wrap:break-word;
+		}
+		.wp-plugin-check-code code {
+			line-height:1.7em
+		}
+		</style>
+	HTML;
+
+
```
Comment (mukeshpanchal27) [inline admin/admin.php]:
```suggestion
```

Remove extra line

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @bordoni, LGTM.
